### ISSUE TITLE
Install SOFA

### ISSUE THREAD

**Issue by Ziemnono** [Ziemnono/caribou_IGA#1]
A first requirement is to install SOFA, I would recommend fixing the version to 21.06.
The documentation can be found here: https://www.sofa-framework.org/download/

The website is currently down but you can follow the installation steps here (only for SOFA do not install the rest): https://github.com/Ziemnono/SofaSimpleForceField_FEniCS

**Comment by bhagath555** [comment]
SOFA 21.06 is installed with the help of below command
```sudo apt install qtbase5-dev libqt5charts5-dev libqt5opengl5-dev libopengl0 libeigen3-dev libglew-dev zlib1g-dev libboost-dev libboost-filesystem-dev g++ cmake git
export SOFA_SRC=/home/bhagath/DOcuments/first/sofa
export SOFA_ROOT=/home/bhagath/DOcuments/first/build/install
git clone -b v21.06 https://github.com/sofa-framework/sofa.git $SOFA_SRC
cmake -DCMAKE_INSTALL_PREFIX=$SOFA_ROOT -DCMAKE_BUILD_TYPE=Release -S $SOFA_SRC -B $SOFA_SRC/build
cmake --build $SOFA_SRC/build -j4
cmake --install $SOFA_SRC/build
