### ISSUE TITLE
Install Caribou

### ISSUE THREAD

**Issue by Ziemnono** [Ziemnono/caribou_IGA#2]
The development will be done with the current Caribou plugin, the building step can be found here:
https://caribou.readthedocs.io/en/latest/Building.html

Careful, you will have to also install SofaPython3 in the doc, choose the same version as your SOFA installation.

**Comment by bhagath555** [comment]
Caribou installed as an external plugin. For the proper installation, I have followed [Caribou](https://caribou.readthedocs.io/en/latest/Building.html) page, defined  *SOFA_ROOT SOFAPYTHON3_ROOT SP3_ROOT CARIBOU_ROOT* paths in .bashrc, after the inserted `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$SOFA_ROOT/lib"` command.
