### ISSUE TITLE
NURBS requirements

### ISSUE THREAD

**Issue by Ziemnono** [Ziemnono/caribou_IGA#4]
@ChintanJansari , could you make a short list of the necessary requirements for using NURBS in IGA?
Ideally, a code snippet describing the simple parameters and outputs of functions such as knot vectors, Gauss points, etc..

**Comment by ChintanJansari** [comment]
@bhagath555 @Ziemnono 
 
Here is the text file with all the requirements from the NURBS patch to use it in IGA. I have given a simple description of them. 
[nurbsdata.txt](https://github.com/Ziemnono/caribou_IGA/files/9653264/nurbsdata.txt)
However, if you have any doubts, you can follow [https://www.sciencedirect.com/science/article/pii/S0378475415001214](https://www.sciencedirect.com/science/article/pii/S0378475415001214), the paper is easy to understand the implementation. Their Matlab codes are also available [https://sourceforge.net/projects/cmcodes/](https://sourceforge.net/projects/cmcodes/) The files consist of all the subroutines required for IGA as well as elasticity examples. Let me know if you have any issues following it.

**Comment by Ziemnono** [comment]
@ChintanJansari thank you very much could you just change the URL of the links it's not going to the right address, once you're done you can close the issue :)
