### ISSUE TITLE
Documentation about IGA

### ISSUE THREAD

**Issue by Ziemnono** [Ziemnono/caribou_IGA#5]
Give some details about the IGA, especially highlighting the differences with FEM.
@bhagath555 you can directly edit this specific page [https://github.com/Ziemnono/caribou_IGA/wiki/IGA-documentation](https://github.com/Ziemnono/caribou_IGA/wiki/IGA-documentation)

**Comment by bhagath555** [comment]
This [Bezier_Extraction IGA.pdf](https://github.com/Ziemnono/caribou_IGA/files/10054051/Bezier_Extraction.IGA.pdf) contained detailed explanation of Isogeometric analysis and bezier extraction (which is important to implement IGA using FEM data structure, lets leave it for time being). The simplified IGA methodology provided  in this [post](https://www.researchgate.net/publication/356040130_Isogeometric_analysis_of_1D_bar). @ChintanJansari, please review the document.

**Comment by bhagath555** [comment]
Below publications will be useful for understanding and computer implementation of IGA 
* [Isogeometric analysis : an overview and computer implementation aspects](https://arxiv.org/pdf/1205.2129.pdf)
* [Static structural and modal analysis using Isogeometric analysis](https://cyberleninka.org/article/n/718471.pdf)
* [Isogeometric finite element data structures based on Bézier extraction of NURBS](https://onlinelibrary.wiley.com/doi/abs/10.1002/nme.2968)

**Comment by Ziemnono** [comment]
@bhagath555 perfect, could you directly edit the wiki [https://github.com/Ziemnono/caribou_IGA/wiki/IGA-documentation](https://github.com/Ziemnono/caribou_IGA/wiki/IGA-documentation), an issue get lost easier than a wiki page.
Many thanks !
